networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8890:80"
    networks:
      - proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app1:
    image: php:8.2-apache
    container_name: app-1
    volumes:
      - ./app1:/var/www/html
    networks:
    - proxy
  
  app2:
    image: php:8.2-apache
    container_name: app-2
    volumes:
      - ./app2:/var/www/html
    networks:
      - proxy
